title: NorthSIM
description: NorthSIM Help and FAQ
theme: just-the-docs
color_scheme: dark

url: https://faq.northsim.com

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jemoji
