title: NorthSIM
description: NorthSIM Help and FAQ
theme: just-the-docs
color_scheme: light
logo: "/assets/images/logo/nslogo100x100.png"
url: https://faq.northsim.com

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jemoji

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Color schemes:
callouts:
  warning:
    title: Notice
    color: red

  new:
    title: New
    color: green