title: NorthSIM
description: NorthSIM Help and FAQ
remote_theme: leakyabstractions/pretty-docs
color_scheme: northsim

url: https://faq.northsim.com

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jemoji

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Color schemes:
callouts:
  highlight:
    title: Instructions
    color: nsyellow